echo "<<<<<{}>======================================================<{}>>>>>"
echo "      |   BANTUAN & CREDITS                                     |"
echo "      |                                                         |"
echo "      |  #BANTUAN                                               |"
echo "      |    Ketikan python2 explor.py untuk tampilan home,       |"
echo "      |    disana terdapat daftar istilah. Cara penggunaan      |"
echo "      |    contoh : python2 explor.py 36.86.63.182 80 350       |"
echo "      |    (36.86.63.182) : alamat ip website                   |"
echo "      |    (80)           : port websitenya                     |"
echo "      |    (350)          : packet virus yang dikirimkan        |"
echo "      |    run pada 3 tab jika masih kurang tambah saja tabnya  |"
echo "      |                                                         |"
echo "      |  #CREDITS                                               |"
echo "      |    Sc ini dibuat oleh ShannModerz dikembangkan dari     |"
echo "      |    beberapa sc ddos yang kemudian di jadikan satu       |"
echo "      |    menjadi sc explor dengan format python2              |"
echo "      |                                                         |"
echo "      |  #SPECIAL THANKS FOR                                    |"
echo "      |    🔵) ShannModerz                                      |"
echo "      |     ©) Faris-Mods                                       |"
echo "      |     ©) Termux                                           |"
echo "      |                                                         |"
echo "      |  #SPECIAL THANKS SC FOR                                 |"
echo "      |     ©) LITEDDOS                                         |"
echo "      |     ©) hammer                                           |"
echo "      |     ©) slowloris                                        |"
echo "      |     ©) Ddos-script                                      |"
echo "<<<<<{}>======================================================<{}>>>>>"
